[package]
name = "share-1password"
version = "0.1.0"
edition = "2021"

[dependencies]
arboard = "3.4.1"
clap = { version = "4.5.17", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.12.0"
chrono = "0.4.38"